name: skillsmatch
description: "A new Flutter project."

publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.3.0
  image_picker: ^1.1.2
  firebase_storage: ^13.3.0
  http: ^1.2.2
  flutter_native_splash: ^2.4.7
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  emoji_picker_flutter: ^4.4.0
  livekit_client: ^2.3.4
  permission_handler: ^11.3.1
  flutter_webrtc: ^1.3.0
  firebase_messaging: ^16.0.0
  record: ^6.1.2
  audioplayers: ^6.5.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/icon/icon.png"

  adaptive_icon_background: "#4F46E5"
  adaptive_icon_foreground: "assets/icon/icon.png"

  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/slika1.png
    - assets/images/slika2.png
    - assets/images/slika3.png
    - assets/images/slika4.png
    - assets/images/slika5.png
    - assets/images/slika6.png
    - assets/images/slika7.png
    - assets/images/slika8.png
    - assets/images/slika9.png
    - assets/images/slika10.png
    - assets/images/slika11.jpeg
    - assets/images/slika12.png
    - assets/images/rakun.png
    - assets/images/skupnost.png

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/slika12.png

  android: true
  ios: true

  fullscreen: true