# Identifikacija projekta na tvom SonarQube serveru
sonar.projectKey=SkillsMatch
sonar.projectName=SkillsMatch
sonar.projectVersion=1.0

# Lokacija izvornog koda i testova
sonar.sources=lib,pubspec.yaml
sonar.tests=test

# Encoding fajlova (uvek UTF-8 za Flutter)
sonar.sourceEncoding=UTF-8

# Isključivanje generisanih fajlova koji bi "zagadili" analizu
sonar.exclusions=**/*.g.dart, **/*.freezed.dart, **/*.gen.dart, build/**, ios/**, android/**, .dart_tool/**, test/**

# (Opciono) Eksplicitno postavljanje načina rada analizatora
sonar.dart.analyzer.mode=FLUTTER