// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7SIKmpCBy8DqokrSEGnT7Dnp-mmU1ZXM',
    appId: '1:786145145910:web:468b375c081613f6365497',
    messagingSenderId: '786145145910',
    projectId: 'skillsmatch-48f64',
    authDomain: 'skillsmatch-48f64.firebaseapp.com',
    storageBucket: 'skillsmatch-48f64.firebasestorage.app',
    measurementId: 'G-ST8SR4HG0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBmiEBp604U0YWIq6nKSgk2Cyz8GXl9uY',
    appId: '1:786145145910:android:4040edba7c5e53cb365497',
    messagingSenderId: '786145145910',
    projectId: 'skillsmatch-48f64',
    storageBucket: 'skillsmatch-48f64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj4JKjAxxY_FwyGXHqFvlPUUFx9bY7_HA',
    appId: '1:786145145910:ios:b7e3692a9aefe991365497',
    messagingSenderId: '786145145910',
    projectId: 'skillsmatch-48f64',
    storageBucket: 'skillsmatch-48f64.firebasestorage.app',
    iosBundleId: 'com.example.skillsmatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj4JKjAxxY_FwyGXHqFvlPUUFx9bY7_HA',
    appId: '1:786145145910:ios:b7e3692a9aefe991365497',
    messagingSenderId: '786145145910',
    projectId: 'skillsmatch-48f64',
    storageBucket: 'skillsmatch-48f64.firebasestorage.app',
    iosBundleId: 'com.example.skillsmatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7SIKmpCBy8DqokrSEGnT7Dnp-mmU1ZXM',
    appId: '1:786145145910:web:620a07c36da372c6365497',
    messagingSenderId: '786145145910',
    projectId: 'skillsmatch-48f64',
    authDomain: 'skillsmatch-48f64.firebaseapp.com',
    storageBucket: 'skillsmatch-48f64.firebasestorage.app',
    measurementId: 'G-TS940HBS65',
  );
}
